import { Property, Agent } from "@shared/schema";

// This file contains initial data to populate the application
// In production, this would be replaced with API calls to property data sources

export const mockProperties: Omit<Property, "id" | "createdAt" | "updatedAt">[] = [
  {
    title: "Luxury Manhattan Penthouse",
    address: "432 Park Avenue, Midtown",
    price: 4200000,
    priceType: "sale",
    propertyType: "residential",
    subType: "condo",
    bedrooms: 3,
    bathrooms: 3,
    squareFootage: 2100,
    description: "Stunning penthouse with panoramic city views and luxury finishes throughout.",
    features: ["City Views", "Luxury Finishes", "Concierge", "Gym", "Rooftop Terrace"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600"],
    neighborhood: "Midtown",
    borough: "Manhattan",
    status: "available",
    featured: true,
    agentId: null,
  },
  {
    title: "Historic Brooklyn Townhouse",
    address: "Park Slope, Brooklyn",
    price: 2800000,
    priceType: "sale",
    propertyType: "residential",
    subType: "townhouse",
    bedrooms: 4,
    bathrooms: 3,
    squareFootage: 3200,
    description: "Beautiful historic townhouse with original details and modern updates.",
    features: ["Historic Details", "Garden", "Original Hardwood", "Modern Kitchen"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600"],
    neighborhood: "Park Slope",
    borough: "Brooklyn",
    status: "available",
    featured: true,
    agentId: null,
  },
  {
    title: "Premium Midtown Office",
    address: "1 World Trade Center, Financial District",
    price: 85,
    priceType: "lease",
    propertyType: "commercial",
    subType: "office",
    squareFootage: 5000,
    floor: "45th Floor",
    description: "Premium office space with stunning views and modern amenities.",
    features: ["City Views", "Modern Build-out", "24/7 Access", "Conference Rooms"],
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600"],
    neighborhood: "Financial District",
    borough: "Manhattan",
    status: "available",
    featured: true,
    agentId: null,
  },
  {
    title: "Upper East Side Condo",
    address: "845 Fifth Avenue, UES",
    price: 3500000,
    priceType: "sale",
    propertyType: "residential",
    subType: "condo",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1800,
    description: "Elegant condo with Central Park views and luxury amenities.",
    features: ["Central Park Views", "Doorman", "Marble Bathrooms", "Chef's Kitchen"],
    images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600"],
    neighborhood: "Upper East Side",
    borough: "Manhattan",
    status: "available",
    featured: false,
    agentId: null,
  },
  {
    title: "SoHo Retail Space",
    address: "Broadway, SoHo",
    price: 150,
    priceType: "lease",
    propertyType: "commercial",
    subType: "retail",
    squareFootage: 2500,
    floor: "Ground Floor",
    description: "Prime retail space in the heart of SoHo with excellent foot traffic.",
    features: ["High Foot Traffic", "Large Windows", "Flexible Layout", "Prime Location"],
    images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600"],
    neighborhood: "SoHo",
    borough: "Manhattan",
    status: "available",
    featured: false,
    agentId: null,
  },
];

export const mockAgents: Omit<Agent, "id" | "createdAt" | "updatedAt">[] = [
  {
    name: "Michael Chen",
    title: "Senior Residential Agent",
    email: "mchen@bravadonyc.com",
    phone: "(212) 555-0101",
    bio: "Michael specializes in luxury residential properties throughout Manhattan with over 12 years of experience.",
    experience: "12+ years specializing in Manhattan luxury condominiums",
    specialties: ["Luxury Condos", "Manhattan Properties", "Investment Properties"],
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    linkedinUrl: "https://linkedin.com/in/michael-chen-bre",
  },
  {
    name: "Sarah Johnson",
    title: "Commercial Director",
    email: "sjohnson@bravadonyc.com",
    phone: "(212) 555-0102",
    bio: "Sarah leads our commercial division with extensive experience in office leasing and investment properties.",
    experience: "15+ years in commercial real estate and investment properties",
    specialties: ["Office Leasing", "Investment Properties", "Commercial Sales"],
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    linkedinUrl: "https://linkedin.com/in/sarah-johnson-bre",
  },
  {
    name: "David Rodriguez",
    title: "Investment Specialist",
    email: "drodriguez@bravadonyc.com",
    phone: "(212) 555-0103",
    bio: "David helps clients build and optimize their real estate investment portfolios across all property types.",
    experience: "10+ years helping clients build real estate portfolios",
    specialties: ["Investment Analysis", "Portfolio Management", "Market Research"],
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    linkedinUrl: "https://linkedin.com/in/david-rodriguez-bre",
  },
  {
    name: "Emily Wang",
    title: "Luxury Specialist",
    email: "ewang@bravadonyc.com",
    phone: "(212) 555-0104",
    bio: "Emily focuses on high-end residential properties and provides white-glove service to discerning clients.",
    experience: "8+ years in high-end residential properties across NYC",
    specialties: ["Luxury Residential", "White-glove Service", "High-net-worth Clients"],
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    linkedinUrl: "https://linkedin.com/in/emily-wang-bre",
  },
  {
    name: "Robert Thompson",
    title: "Senior Partner",
    email: "rthompson@bravadonyc.com",
    phone: "(212) 555-0105",
    bio: "Robert is a founding partner with decades of experience in all aspects of New York real estate.",
    experience: "20+ years leading NYC real estate transactions",
    specialties: ["Executive Leadership", "Complex Transactions", "Market Strategy"],
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    linkedinUrl: "https://linkedin.com/in/robert-thompson-bre",
  },
  {
    name: "Jennifer Kim",
    title: "New Development Specialist",
    email: "jkim@bravadonyc.com",
    phone: "(212) 555-0106",
    bio: "Jennifer specializes in new construction projects and pre-construction sales throughout the city.",
    experience: "6+ years specializing in new construction projects",
    specialties: ["New Development", "Pre-construction Sales", "Developer Relations"],
    image: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&h=600",
    linkedinUrl: "https://linkedin.com/in/jennifer-kim-bre",
  },
];
